apiVersion: storage.koor.tech/v1alpha1
kind: KoorCluster
metadata:
  labels:
    app.kubernetes.io/name: koorcluster
    app.kubernetes.io/instance: koorcluster-sample
    app.kubernetes.io/part-of: koor-operator-sdk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: koor-operator-sdk
  name: koorcluster-sample
spec:
  # TODO(user): Add fields here
